[project]
name = "shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "pybase62>=1.0.0",
    "sqlalchemy>=2.1.1",
    "xxhash>=4.0.1",
]

[tool.uv]
package = false

[tool.pylint.main]
init-hook = "import sys; sys.path.append('src')"
load-plugins = ["pylint_per_file_ignores"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.pylint.'messages control']
per-file-ignores = [
    "test/*.py:missing-function-docstring, missing-module-docstring, unused-argument, redefined-outer-name, protected-access"
]
